# gz topic camera_info 
- ros_topic_name: "/camera/rgb/camera_info"
  gz_topic_name: "/camera/rgb/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS